#!/bin/bash
# bootstrap for yadm

# call paru install
arch_install() {
	paru -S "$1" --noconfirm --skipreview --mflags --skipchecksums
	echo "install $1 ok"
}

# Determine whether the package is installed
### usage:
# is_install $dd
# if [[ $? -eq 1 ]] ; then
#  echo ok
# fi
is_install() {
	if [ "$(command -v "$1")" ]; then
		return 1
	else
		return 0
	fi
}

# handle install
handle_install() {
	is_install "$2"

	if [[ $? -eq 1 ]]; then
		arch_install "$1"
	else
		echo "$2 has been installed"
	fi
}

for file in "$HOME"/.config/yadm/program/*; do
	if test -f "$file"; then
		while read -r line; do
			line_arr=($line)
			if ((${#line_arr[@]} <= 1)); then
				arch_install "${line_arr[0]}"
			else
				handle_install "${line_arr[0]}" "${line_arr[1]}"
			fi
		done <"$file"
	fi
	# if test -d "$file"; then
	# 	echo "$file" 是目录
	# fi
done

sudo usermod -aG docker $USER
sudo usermod -aG input $USER
sudo usermod -aG video $USER
